### ISSUE TITLE
GovToken, council and proposal changes.

### ISSUE THREAD

**Issue by zycon91** [CherryNetwork/Cherry-Node#88]
We need to change how the GovToken interacts with the Council and the proposals.

**GovToken changes**
- [x] Seperate Council from `pallet_collective`
- [x] Add `pallet_assets` in the new pallet
- [x] We want to make the council members to vote on proposals with their GovTokens.
- [x] The GovToken will be acting like your "voting power". If you vote yes and you have 30 GovTokens, 30 yes votes will be added to the proposal. 
- [x] For any proposal to be approved, we want a minimum of 30% of the total GovTokens to participate in the proposal.

**Proposal Changes**
- [x] If a proposal (non-recurring) gets approved, but the treasury cannot fund it, the proposal will be rolled over the next spend period, but the votes will become NULL.
- [x] If a recurring proposal gets approved, but the treasury cannot fund a segment of it in a spend period, the proposal will lose that segment.

**Council Changes**
- [x] Remove the maximum seats.

**Comment by charmitro** [comment]
Council is an instance of `pallet-collective`. Therefore we should create a new pallet containing named `pallet-council`. I'll start implementing this and see if it actually fit our specifications. 
cc. @zycon91

**Comment by zycon91** [comment]
> Council is an instance of `pallet-collective`. Therefore we should create a new pallet containing named `pallet-council`. I'll start implementing this and see if it actually fit our specifications. cc. @zycon91

Totally agree. Either `council` or `technical_committee` should be in each own pallet. I think it makes more sense to move `council` to a new pallet (`pallet_council` like you said).

**Comment by charmitro** [comment]
Let's finish the tests for theses changes and close this issue. @zycon91 ping me when you're ready

**Comment by zycon91** [comment]
All the tasks are done and have been tested in the UI and via some unit tests. Ready to close.
